language: c

compiler:
  - clang
  - gcc

os:
  - linux
  - osx

matrix:
  include:
    - compiler: gcc
      os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-6
      env:
        - MATRIX_EVAL="CC=gcc-6 && CXX=g++-6"

script: ./autogen.sh && ./configure && make
