/* Do not edit this file. It was automatically generated. */

#ifndef HEADER_CmdLineScreen
#define HEADER_CmdLineScreen

#include "InfoScreen.h"

typedef struct CmdLineScreen_ {
   InfoScreen super;
} CmdLineScreen;

extern InfoScreenClass CmdLineScreen_class;

CmdLineScreen* CmdLineScreen_new(Process* process);

void CmdLineScreen_delete(Object* this);

void CmdLineScreen_draw(InfoScreen* this);

void CmdLineScreen_scan(InfoScreen* this);

#endif
