/* Do not edit this file. It was automatically generated. */

#ifndef HEADER_Filter
#define HEADER_Filter
/*
htop - Filter.h
(C) 2004-2011 Hisham H. Muhammad
Released under the GNU GPL, see the COPYING file
in the source distribution for its full text.
*/

#include <regex.h>
#include <stdbool.h>

typedef struct Filter_ {
   bool regex;
   bool exclude;
   char* rawFilter;
   regex_t regexFilter;
} Filter;


Filter* Filter_new(const char* filterString);

bool Filter_test(Filter* this, const char* str);

void Filter_delete(Filter* this);

#endif
