/* Do not edit this file. It was automatically generated. */

#ifndef HEADER_KernelVersion
#define HEADER_KernelVersion
/*
htop - UptimeMeter.h
(C) 2004-2011 Hisham H. Muhammad
Released under the GNU GPL, see the COPYING file
in the source distribution for its full text.
*/

#include "Meter.h"

extern int KernelVersionMeter_attributes[];

extern MeterClass KernelVersionMeter_class;

#endif
