/* Do not edit this file. It was automatically generated. */

#ifndef HEADER_MemoryMeter
#define HEADER_MemoryMeter
/*
htop - MemoryMeter.h
(C) 2004-2011 Hisham H. Muhammad
Released under the GNU GPL, see the COPYING file
in the source distribution for its full text.
*/

#include "Meter.h"

#define KILOBYTE 1
#define MEGABYTE 1024
#define GIGABYTE 1048576

extern int MemoryMeter_attributes[];

extern MeterClass MemoryMeter_class;

#endif
