/* Do not edit this file. It was automatically generated. */

#ifndef HEADER_Meter
#define HEADER_Meter
/*
htop - Meter.h
(C) 2004-2011 Hisham H. Muhammad
Released under the GNU GPL, see the COPYING file
in the source distribution for its full text.
*/

#define METER_BUFFER_LEN 128

#include "ListItem.h"
#include "ProcessList.h"

typedef struct Meter_ Meter;

typedef void(*Meter_Init)(Meter*);
typedef void(*Meter_Done)(Meter*);
typedef void(*Meter_UpdateMode)(Meter*, int);
typedef void(*Meter_SetValues)(Meter*, char*, int);
typedef void(*Meter_Draw)(Meter*, int, int, int);

typedef struct MeterClass_ {
   ObjectClass super;
   const Meter_Init init;
   const Meter_Done done;
   const Meter_UpdateMode updateMode;
   const Meter_Draw draw;
   const Meter_SetValues setValues;
   const int defaultMode;
   const double total;
   const int* attributes;
   const char* name;
   const char* uiName;
   const char* caption;
   const char maxItems;
   char curItems;
} MeterClass;

#define As_Meter(htop_this_)                ((MeterClass*)((htop_this_)->super.klass))
#define Meter_initFn(htop_this_)            As_Meter(htop_this_)->init
#define Meter_init(htop_this_)              As_Meter(htop_this_)->init((Meter*)(htop_this_))
#define Meter_done(htop_this_)              As_Meter(htop_this_)->done((Meter*)(htop_this_))
#define Meter_updateModeFn(htop_this_)      As_Meter(htop_this_)->updateMode
#define Meter_updateMode(htop_this_, m_)    As_Meter(htop_this_)->updateMode((Meter*)(htop_this_), m_)
#define Meter_drawFn(htop_this_)            As_Meter(htop_this_)->draw
#define Meter_doneFn(htop_this_)            As_Meter(htop_this_)->done
#define Meter_setValues(htop_this_, c_, i_) As_Meter(htop_this_)->setValues((Meter*)(htop_this_), c_, i_)
#define Meter_defaultMode(htop_this_)       As_Meter(htop_this_)->defaultMode
#define Meter_getItems(htop_this_)          As_Meter(htop_this_)->curItems
#define Meter_setItems(htop_this_, n_)      As_Meter(htop_this_)->curItems = (n_)
#define Meter_attributes(htop_this_)        As_Meter(htop_this_)->attributes
#define Meter_name(htop_this_)              As_Meter(htop_this_)->name
#define Meter_uiName(htop_this_)            As_Meter(htop_this_)->uiName

struct Meter_ {
   Object super;
   Meter_Draw draw;
   
   char* caption;
   int mode;
   int param;
   void* drawData;
   int h;
   ProcessList* pl;
   double* values;
   double total;
};

typedef struct MeterMode_ {
   Meter_Draw draw;
   const char* uiName;
   int h;
} MeterMode;

typedef enum {
   CUSTOM_METERMODE = 0,
   BAR_METERMODE,
   TEXT_METERMODE,
   GRAPH_METERMODE,
   LED_METERMODE,
   LAST_METERMODE
} MeterModeId;

typedef struct GraphData_ {
   struct timeval time;
   double values[METER_BUFFER_LEN];
} GraphData;


#ifndef MIN
#define MIN(a,b) ((a)<(b)?(a):(b))
#endif
#ifndef MAX
#define MAX(a,b) ((a)>(b)?(a):(b))
#endif

extern MeterClass Meter_class;

extern MeterClass* Meter_types[];

Meter* Meter_new(ProcessList* pl, int param, MeterClass* type);

void Meter_delete(Object* cast);

void Meter_setCaption(Meter* htop_this, const char* caption);

void Meter_setMode(Meter* htop_this, int modeIndex);

ListItem* Meter_toListItem(Meter* htop_this);

/* ---------- TextMeterMode ---------- */

/* ---------- BarMeterMode ---------- */

/* ---------- GraphMeterMode ---------- */

#define DrawDot(a,y,c) do { attrset(a); mvaddch(y, x+k, c); } while(0)

/* ---------- LEDMeterMode ---------- */

extern MeterMode* Meter_modes[];

#endif
