/* Do not edit this file. It was automatically generated. */

#ifndef HEADER_NetTrafficMeter
#define HEADER_NetTrafficMeter

#include "Meter.h"

extern int NetTrafficMeter_attributes[];

extern MeterClass NetTrafficMeter_class;

#endif
