/* Do not edit this file. It was automatically generated. */

#ifndef HEADER_UnameMeter
#define HEADER_UnameMeter
/*
htop - UnameMeter.h
(C) 2004-2011 Hisham H. Muhammad
Released under the GNU GPL, see the COPYING file
in the source distribution for its full text.
*/

#include "Meter.h"

extern int UnameMeter_attributes[];

extern MeterClass UnameMeter_class;

#endif
