/* Do not edit this file. It was automatically generated. */

#ifndef HEADER_Vector
#define HEADER_Vector
/*
htop - Vector.h
(C) 2004-2011 Hisham H. Muhammad
Released under the GNU GPL, see the COPYING file
in the source distribution for its full text.
*/

#include "Object.h"

#define swap(a_,x_,y_) do{ void* tmp_ = a_[x_]; a_[x_] = a_[y_]; a_[y_] = tmp_; }while(0)

#ifndef DEFAULT_SIZE
#define DEFAULT_SIZE -1
#endif

typedef struct Vector_ {
   Object **array;
   ObjectClass* type;
   int arraySize;
   int growthRate;
   int items;
   bool owner;
} Vector;


Vector* Vector_new(ObjectClass* type, bool owner, int size);

void Vector_delete(Vector* htop_this);

#ifdef DEBUG

int Vector_count(Vector* htop_this);

#endif

void Vector_prune(Vector* htop_this);

// If I were to use only one sorting algorithm for both cases, it would probably be htop_this one:
/*

*/

void Vector_quickSort(Vector* htop_this);

void Vector_insertionSort(Vector* htop_this);

void Vector_insert(Vector* htop_this, int idx, void* data_);

Object* Vector_take(Vector* htop_this, int idx);

Object* Vector_remove(Vector* htop_this, int idx);

void Vector_moveUp(Vector* htop_this, int idx);

void Vector_moveDown(Vector* htop_this, int idx);

void Vector_set(Vector* htop_this, int idx, void* data_);

#ifdef DEBUG

extern Object* Vector_get(Vector* htop_this, int idx);

#else

#define Vector_get(v_, idx_) ((v_)->array[idx_])

#endif

extern int Vector_size(Vector* htop_this);

/*

*/

void Vector_add(Vector* htop_this, void* data_);

extern int Vector_indexOf(Vector* htop_this, void* search_, Object_Compare compare);

#endif
