/* Do not edit this file. It was automatically generated. */

#ifndef HEADER_SolarisMemoryMeter
#define HEADER_SolarisMemoryMeter
/*
htop - SolarisMemoryMeter.h
(C) 2004-2011 Hisham H. Muhammad
Released under the GNU GPL, see the COPYING file
in the source distribution for its full text.
*/

#include "Meter.h"

extern int SolarisMemoryMeter_attributes[];

extern MeterClass SolarisMemoryMeter_class;

#endif
