/* Do not edit this file. It was automatically generated. */

#ifndef HEADER_SolarisProcess
#define HEADER_SolarisProcess
/*
htop - UnsupportedProcess.h
(C) 2015 Hisham H. Muhammad
Released under the GNU GPL, see the COPYING file
in the source distribution for its full text.
*/

#include "Settings.h"

#define Process_delete SolarisProcess_delete


Process* SolarisProcess_new(Settings* settings);

void SolarisProcess_delete(Object* cast);


#endif
