/* Do not edit this file. It was automatically generated. */

#ifndef HEADER_ZswapMeter
#define HEADER_ZswapMeter
/*
htop - ZswapMeter.h
(C) 2004-2011 Hisham H. Muhammad
Released under the GNU GPL, see the COPYING file
in the source distribution for its full text.
*/

#include "Meter.h"

extern int ZswapMeter_attributes[];

extern MeterClass ZswapMeter_class;

#endif
